2024-10-28 21:18:07,641 | INFO | Starting hyperparameter search
2024-10-28 21:18:07,641 | INFO | Hyperparameter search space:
2024-10-28 21:18:07,641 | INFO | {
  "clip_lr": [
    1e-05,
    0.0001,
    5e-06
  ],
  "predictor_lr": [
    5e-05,
    0.0005,
    0.001
  ],
  "weight_decay": [
    0.001,
    0.05,
    0.1
  ],
  "beta1": [
    0.9,
    0.95
  ],
  "beta2": [
    0.999,
    0.9999
  ],
  "hidden_dim": [
    256,
    768,
    1024
  ],
  "dropout_rate": [
    0.1,
    0.3,
    0.4,
    0.5
  ],
  "num_hidden_layers": [
    1,
    2,
    3
  ]
}
2024-10-28 21:18:16,675 | INFO | Dataset loaded successfully with 70213 samples
2024-10-28 21:18:16,679 | INFO | Dataset split: 63192 train, 7021 validation samples
/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/utils/data/dataloader.py:557: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
2024-10-28 21:18:16,680 | INFO | Attribute dimensions:
2024-10-28 21:18:16,680 | INFO | {
  "Kurtis_color": 13,
  "Kurtis_fit_shape": 2,
  "Kurtis_length": 2,
  "Kurtis_occasion": 2,
  "Kurtis_ornamentation": 2,
  "Kurtis_pattern": 2,
  "Kurtis_print_or_pattern_type": 2,
  "Kurtis_sleeve_length": 3,
  "Kurtis_sleeve_styling": 2,
  "Men Tshirts_color": 4,
  "Men Tshirts_neck": 2,
  "Men Tshirts_pattern": 2,
  "Men Tshirts_print_or_pattern_type": 3,
  "Men Tshirts_sleeve_length": 2,
  "Sarees_blouse_pattern": 4,
  "Sarees_border": 6,
  "Sarees_border_width": 3,
  "Sarees_color": 8,
  "Sarees_occasion": 4,
  "Sarees_ornamentation": 3,
  "Sarees_pallu_details": 4,
  "Sarees_pattern": 5,
  "Sarees_print_or_pattern_type": 9,
  "Sarees_transparency": 2,
  "Women Tops & Tunics_color": 12,
  "Women Tops & Tunics_fit_shape": 4,
  "Women Tops & Tunics_length": 2,
  "Women Tops & Tunics_neck_collar": 7,
  "Women Tops & Tunics_occasion": 2,
  "Women Tops & Tunics_pattern": 3,
  "Women Tops & Tunics_print_or_pattern_type": 6,
  "Women Tops & Tunics_sleeve_length": 4,
  "Women Tops & Tunics_sleeve_styling": 4,
  "Women Tops & Tunics_surface_styling": 6,
  "Women Tshirts_color": 7,
  "Women Tshirts_fit_shape": 3,
  "Women Tshirts_length": 3,
  "Women Tshirts_pattern": 3,
  "Women Tshirts_print_or_pattern_type": 6,
  "Women Tshirts_sleeve_length": 3,
  "Women Tshirts_sleeve_styling": 2,
  "Women Tshirts_surface_styling": 2
}
2024-10-28 21:18:16,755 | INFO | 
Initialized model with architecture parameters:
2024-10-28 21:18:16,755 | INFO | Hidden Dim: 256, Dropout: 0.1, Layers: 1
2024-10-28 21:18:16,755 | INFO | 
Starting training with optimizer parameters:
2024-10-28 21:18:16,755 | INFO | CLIP LR: 1e-05, Predictor LR: 5e-05, Weight Decay: 0.001, Beta1: 0.9, Beta2: 0.999
2024-10-28 21:18:16,756 | INFO | Starting new training run with validation
2024-10-28 21:18:16,757 | INFO | Training hyperparameters:
2024-10-28 21:18:16,757 | INFO | {
  "clip_lr": 1e-05,
  "predictor_lr": 5e-05,
  "weight_decay": 0.001,
  "beta1": 0.9,
  "beta2": 0.999,
  "num_epochs": 40,
  "patience": 10,
  "device": "cuda",
  "model_architecture": "CategoryAwareAttributePredictor(\n  (attribute_predictors): ModuleDict(\n    (Kurtis_color): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=13, bias=True)\n    )\n    (Kurtis_fit_shape): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=2, bias=True)\n    )\n    (Kurtis_length): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=2, bias=True)\n    )\n    (Kurtis_occasion): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=2, bias=True)\n    )\n    (Kurtis_ornamentation): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=2, bias=True)\n    )\n    (Kurtis_pattern): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=2, bias=True)\n    )\n    (Kurtis_print_or_pattern_type): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=2, bias=True)\n    )\n    (Kurtis_sleeve_length): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=3, bias=True)\n    )\n    (Kurtis_sleeve_styling): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=2, bias=True)\n    )\n    (Men Tshirts_color): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=4, bias=True)\n    )\n    (Men Tshirts_neck): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=2, bias=True)\n    )\n    (Men Tshirts_pattern): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=2, bias=True)\n    )\n    (Men Tshirts_print_or_pattern_type): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=3, bias=True)\n    )\n    (Men Tshirts_sleeve_length): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=2, bias=True)\n    )\n    (Sarees_blouse_pattern): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=4, bias=True)\n    )\n    (Sarees_border): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=6, bias=True)\n    )\n    (Sarees_border_width): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=3, bias=True)\n    )\n    (Sarees_color): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=8, bias=True)\n    )\n    (Sarees_occasion): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=4, bias=True)\n    )\n    (Sarees_ornamentation): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=3, bias=True)\n    )\n    (Sarees_pallu_details): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=4, bias=True)\n    )\n    (Sarees_pattern): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=5, bias=True)\n    )\n    (Sarees_print_or_pattern_type): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=9, bias=True)\n    )\n    (Sarees_transparency): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=2, bias=True)\n    )\n    (Women Tops & Tunics_color): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=12, bias=True)\n    )\n    (Women Tops & Tunics_fit_shape): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=4, bias=True)\n    )\n    (Women Tops & Tunics_length): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=2, bias=True)\n    )\n    (Women Tops & Tunics_neck_collar): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=7, bias=True)\n    )\n    (Women Tops & Tunics_occasion): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=2, bias=True)\n    )\n    (Women Tops & Tunics_pattern): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=3, bias=True)\n    )\n    (Women Tops & Tunics_print_or_pattern_type): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=6, bias=True)\n    )\n    (Women Tops & Tunics_sleeve_length): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=4, bias=True)\n    )\n    (Women Tops & Tunics_sleeve_styling): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=4, bias=True)\n    )\n    (Women Tops & Tunics_surface_styling): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=6, bias=True)\n    )\n    (Women Tshirts_color): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=7, bias=True)\n    )\n    (Women Tshirts_fit_shape): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=3, bias=True)\n    )\n    (Women Tshirts_length): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=3, bias=True)\n    )\n    (Women Tshirts_pattern): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=3, bias=True)\n    )\n    (Women Tshirts_print_or_pattern_type): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=6, bias=True)\n    )\n    (Women Tshirts_sleeve_length): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=3, bias=True)\n    )\n    (Women Tshirts_sleeve_styling): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=2, bias=True)\n    )\n    (Women Tshirts_surface_styling): Sequential(\n      (0): Linear(in_features=768, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Dropout(p=0.1, inplace=False)\n      (3): Linear(in_features=256, out_features=2, bias=True)\n    )\n  )\n)"
}
2024-10-28 21:18:24,989 | INFO | CLIP model loaded successfully
Training Progress:   0%|          | 0/40 [00:00<?, ?it/s]2024-10-28 21:18:24,994 | INFO | Starting epoch 1/40

Epoch 1/40 [Train]:   0%|          | 0/1975 [00:00<?, ?it/s][A2024-10-28 21:18:32,621 | ERROR | Error in batch 0: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   0%|          | 1/1975 [00:07<4:11:10,  7.63s/it][A2024-10-28 21:18:32,783 | ERROR | Error in batch 1: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   0%|          | 2/1975 [00:07<1:46:18,  3.23s/it][A2024-10-28 21:18:32,994 | ERROR | Error in batch 2: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   0%|          | 3/1975 [00:07<1:00:54,  1.85s/it][A2024-10-28 21:18:33,177 | ERROR | Error in batch 3: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   0%|          | 4/1975 [00:08<39:13,  1.19s/it]  [A2024-10-28 21:18:33,447 | ERROR | Error in batch 4: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   0%|          | 5/1975 [00:08<28:15,  1.16it/s][A2024-10-28 21:18:33,699 | ERROR | Error in batch 5: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   0%|          | 6/1975 [00:08<21:27,  1.53it/s][A2024-10-28 21:18:33,902 | ERROR | Error in batch 6: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   0%|          | 7/1975 [00:08<16:36,  1.97it/s][A2024-10-28 21:18:34,092 | ERROR | Error in batch 7: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   0%|          | 8/1975 [00:09<13:18,  2.46it/s][A2024-10-28 21:18:34,365 | ERROR | Error in batch 8: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   0%|          | 9/1975 [00:09<11:55,  2.75it/s][A2024-10-28 21:18:34,589 | ERROR | Error in batch 9: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   1%|          | 10/1975 [00:09<10:30,  3.12it/s][A2024-10-28 21:18:34,848 | ERROR | Error in batch 10: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   1%|          | 11/1975 [00:09<09:53,  3.31it/s][A2024-10-28 21:18:34,973 | ERROR | Error in batch 11: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   1%|          | 12/1975 [00:09<08:07,  4.03it/s][A2024-10-28 21:18:35,226 | ERROR | Error in batch 12: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   1%|          | 13/1975 [00:10<08:09,  4.01it/s][A2024-10-28 21:18:35,562 | ERROR | Error in batch 13: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   1%|          | 14/1975 [00:10<09:00,  3.63it/s][A2024-10-28 21:18:35,809 | ERROR | Error in batch 14: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   1%|          | 15/1975 [00:10<08:43,  3.74it/s][A2024-10-28 21:18:36,031 | ERROR | Error in batch 15: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   1%|          | 16/1975 [00:11<08:16,  3.94it/s][A2024-10-28 21:18:36,604 | ERROR | Error in batch 16: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   1%|          | 17/1975 [00:11<11:24,  2.86it/s][A2024-10-28 21:18:36,804 | ERROR | Error in batch 17: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   1%|          | 18/1975 [00:11<09:55,  3.28it/s][A2024-10-28 21:18:37,079 | ERROR | Error in batch 18: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   1%|          | 19/1975 [00:12<09:38,  3.38it/s][A2024-10-28 21:18:37,307 | ERROR | Error in batch 19: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   1%|          | 20/1975 [00:12<08:58,  3.63it/s][A2024-10-28 21:18:37,639 | ERROR | Error in batch 20: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   1%|          | 21/1975 [00:12<09:31,  3.42it/s][A2024-10-28 21:18:37,822 | ERROR | Error in batch 21: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   1%|          | 22/1975 [00:12<08:26,  3.85it/s][A2024-10-28 21:18:38,081 | ERROR | Error in batch 22: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   1%|          | 23/1975 [00:13<08:26,  3.86it/s][A2024-10-28 21:18:38,352 | ERROR | Error in batch 23: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   1%|          | 24/1975 [00:13<08:33,  3.80it/s][A2024-10-28 21:18:38,881 | ERROR | Error in batch 24: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   1%|▏         | 25/1975 [00:13<11:08,  2.92it/s][A2024-10-28 21:18:39,143 | ERROR | Error in batch 25: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   1%|▏         | 26/1975 [00:14<10:20,  3.14it/s][A2024-10-28 21:18:39,351 | ERROR | Error in batch 26: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   1%|▏         | 27/1975 [00:14<09:15,  3.50it/s][A2024-10-28 21:18:39,524 | ERROR | Error in batch 27: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   1%|▏         | 28/1975 [00:14<08:09,  3.97it/s][A2024-10-28 21:18:40,118 | ERROR | Error in batch 28: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   1%|▏         | 29/1975 [00:15<11:29,  2.82it/s][A2024-10-28 21:18:40,488 | ERROR | Error in batch 29: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   2%|▏         | 30/1975 [00:15<11:37,  2.79it/s][A2024-10-28 21:18:40,589 | ERROR | Error in batch 30: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   2%|▏         | 31/1975 [00:15<09:07,  3.55it/s][A2024-10-28 21:18:40,905 | ERROR | Error in batch 31: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   2%|▏         | 32/1975 [00:15<09:27,  3.43it/s][A2024-10-28 21:18:41,381 | ERROR | Error in batch 32: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   2%|▏         | 33/1975 [00:16<11:13,  2.88it/s][A2024-10-28 21:18:41,591 | ERROR | Error in batch 33: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   2%|▏         | 34/1975 [00:16<09:54,  3.27it/s][A2024-10-28 21:18:41,815 | ERROR | Error in batch 34: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   2%|▏         | 35/1975 [00:16<09:05,  3.55it/s][A2024-10-28 21:18:42,169 | ERROR | Error in batch 35: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   2%|▏         | 36/1975 [00:17<09:47,  3.30it/s][A2024-10-28 21:18:42,380 | ERROR | Error in batch 36: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   2%|▏         | 37/1975 [00:17<08:53,  3.63it/s][A2024-10-28 21:18:42,596 | ERROR | Error in batch 37: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   2%|▏         | 38/1975 [00:17<08:19,  3.88it/s][A2024-10-28 21:18:42,772 | ERROR | Error in batch 38: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   2%|▏         | 39/1975 [00:17<07:31,  4.29it/s][A2024-10-28 21:18:43,052 | ERROR | Error in batch 39: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   2%|▏         | 40/1975 [00:18<07:58,  4.04it/s][A2024-10-28 21:18:43,612 | ERROR | Error in batch 40: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   2%|▏         | 41/1975 [00:18<10:59,  2.93it/s][A2024-10-28 21:18:43,866 | ERROR | Error in batch 41: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   2%|▏         | 42/1975 [00:18<10:08,  3.18it/s][A2024-10-28 21:18:44,108 | ERROR | Error in batch 42: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   2%|▏         | 43/1975 [00:19<09:26,  3.41it/s][A2024-10-28 21:18:44,437 | ERROR | Error in batch 43: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   2%|▏         | 44/1975 [00:19<09:46,  3.29it/s][A2024-10-28 21:18:44,868 | ERROR | Error in batch 44: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   2%|▏         | 45/1975 [00:19<11:00,  2.92it/s][A2024-10-28 21:18:45,076 | ERROR | Error in batch 45: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   2%|▏         | 46/1975 [00:20<09:42,  3.31it/s][A2024-10-28 21:18:45,329 | ERROR | Error in batch 46: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   2%|▏         | 47/1975 [00:20<09:13,  3.48it/s][A2024-10-28 21:18:45,705 | ERROR | Error in batch 47: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   2%|▏         | 48/1975 [00:20<10:05,  3.18it/s][A2024-10-28 21:18:45,942 | ERROR | Error in batch 48: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   2%|▏         | 49/1975 [00:20<09:19,  3.44it/s][A2024-10-28 21:18:46,195 | ERROR | Error in batch 49: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   3%|▎         | 50/1975 [00:21<08:57,  3.58it/s][A2024-10-28 21:18:46,466 | ERROR | Error in batch 50: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   3%|▎         | 51/1975 [00:21<08:52,  3.61it/s][A2024-10-28 21:18:46,799 | ERROR | Error in batch 51: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   3%|▎         | 52/1975 [00:21<09:24,  3.41it/s][A2024-10-28 21:18:47,065 | ERROR | Error in batch 52: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   3%|▎         | 53/1975 [00:22<09:08,  3.50it/s][A2024-10-28 21:18:47,285 | ERROR | Error in batch 53: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   3%|▎         | 54/1975 [00:22<08:30,  3.76it/s][A2024-10-28 21:18:47,601 | ERROR | Error in batch 54: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   3%|▎         | 55/1975 [00:22<08:59,  3.56it/s][A2024-10-28 21:18:47,752 | ERROR | Error in batch 55: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   3%|▎         | 56/1975 [00:22<07:44,  4.13it/s][A2024-10-28 21:18:48,048 | ERROR | Error in batch 56: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   3%|▎         | 57/1975 [00:23<08:15,  3.87it/s][A2024-10-28 21:18:48,494 | ERROR | Error in batch 57: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   3%|▎         | 58/1975 [00:23<10:02,  3.18it/s][A2024-10-28 21:18:48,720 | ERROR | Error in batch 58: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   3%|▎         | 59/1975 [00:23<09:11,  3.47it/s][A2024-10-28 21:18:48,881 | ERROR | Error in batch 59: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   3%|▎         | 60/1975 [00:23<07:58,  4.00it/s][A2024-10-28 21:18:49,094 | ERROR | Error in batch 60: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   3%|▎         | 61/1975 [00:24<07:36,  4.19it/s][A2024-10-28 21:18:49,696 | ERROR | Error in batch 61: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   3%|▎         | 62/1975 [00:24<11:05,  2.88it/s][A2024-10-28 21:18:49,888 | ERROR | Error in batch 62: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   3%|▎         | 63/1975 [00:24<09:35,  3.32it/s][A2024-10-28 21:18:50,102 | ERROR | Error in batch 63: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   3%|▎         | 64/1975 [00:25<08:45,  3.64it/s][A2024-10-28 21:18:50,337 | ERROR | Error in batch 64: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   3%|▎         | 65/1975 [00:25<08:21,  3.80it/s][A2024-10-28 21:18:51,002 | ERROR | Error in batch 65: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   3%|▎         | 66/1975 [00:26<12:11,  2.61it/s][A2024-10-28 21:18:51,218 | ERROR | Error in batch 66: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   3%|▎         | 67/1975 [00:26<10:36,  3.00it/s][A2024-10-28 21:18:51,494 | ERROR | Error in batch 67: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   3%|▎         | 68/1975 [00:26<10:03,  3.16it/s][A2024-10-28 21:18:51,704 | ERROR | Error in batch 68: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   3%|▎         | 69/1975 [00:26<09:01,  3.52it/s][A2024-10-28 21:18:52,387 | ERROR | Error in batch 69: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   4%|▎         | 70/1975 [00:27<12:49,  2.48it/s][A2024-10-28 21:18:52,589 | ERROR | Error in batch 70: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   4%|▎         | 71/1975 [00:27<10:53,  2.91it/s][A2024-10-28 21:18:52,766 | ERROR | Error in batch 71: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   4%|▎         | 72/1975 [00:27<09:18,  3.41it/s][A2024-10-28 21:18:53,053 | ERROR | Error in batch 72: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   4%|▎         | 73/1975 [00:28<09:14,  3.43it/s][A2024-10-28 21:18:53,267 | ERROR | Error in batch 73: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   4%|▎         | 74/1975 [00:28<08:30,  3.73it/s][A2024-10-28 21:18:53,481 | ERROR | Error in batch 74: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   4%|▍         | 75/1975 [00:28<07:58,  3.97it/s][A2024-10-28 21:18:53,714 | ERROR | Error in batch 75: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   4%|▍         | 76/1975 [00:28<07:47,  4.06it/s][A2024-10-28 21:18:54,014 | ERROR | Error in batch 76: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   4%|▍         | 77/1975 [00:29<08:17,  3.81it/s][A2024-10-28 21:18:54,317 | ERROR | Error in batch 77: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   4%|▍         | 78/1975 [00:29<08:40,  3.64it/s][A2024-10-28 21:18:54,491 | ERROR | Error in batch 78: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   4%|▍         | 79/1975 [00:29<07:43,  4.09it/s][A2024-10-28 21:18:54,804 | ERROR | Error in batch 79: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   4%|▍         | 80/1975 [00:29<08:22,  3.77it/s][A2024-10-28 21:18:55,111 | ERROR | Error in batch 80: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   4%|▍         | 81/1975 [00:30<08:45,  3.60it/s][A2024-10-28 21:18:55,597 | ERROR | Error in batch 81: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   4%|▍         | 82/1975 [00:30<10:43,  2.94it/s][A2024-10-28 21:18:55,850 | ERROR | Error in batch 82: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   4%|▍         | 83/1975 [00:30<09:53,  3.19it/s][A2024-10-28 21:18:56,018 | ERROR | Error in batch 83: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   4%|▍         | 84/1975 [00:31<08:31,  3.70it/s][A2024-10-28 21:18:56,298 | ERROR | Error in batch 84: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   4%|▍         | 85/1975 [00:31<08:36,  3.66it/s][A2024-10-28 21:18:56,664 | ERROR | Error in batch 85: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   4%|▍         | 86/1975 [00:31<09:28,  3.32it/s][A2024-10-28 21:18:56,928 | ERROR | Error in batch 86: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   4%|▍         | 87/1975 [00:31<09:07,  3.45it/s][A2024-10-28 21:18:57,236 | ERROR | Error in batch 87: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   4%|▍         | 88/1975 [00:32<09:17,  3.39it/s][A2024-10-28 21:18:57,427 | ERROR | Error in batch 88: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   5%|▍         | 89/1975 [00:32<08:17,  3.79it/s][A2024-10-28 21:18:57,966 | ERROR | Error in batch 89: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   5%|▍         | 90/1975 [00:32<10:53,  2.89it/s][A2024-10-28 21:18:58,185 | ERROR | Error in batch 90: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   5%|▍         | 91/1975 [00:33<09:41,  3.24it/s][A2024-10-28 21:18:58,450 | ERROR | Error in batch 91: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   5%|▍         | 92/1975 [00:33<09:16,  3.39it/s][A2024-10-28 21:18:58,695 | ERROR | Error in batch 92: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   5%|▍         | 93/1975 [00:33<08:47,  3.57it/s][A2024-10-28 21:18:58,931 | ERROR | Error in batch 93: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   5%|▍         | 94/1975 [00:33<08:21,  3.75it/s][A2024-10-28 21:18:59,186 | ERROR | Error in batch 94: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   5%|▍         | 95/1975 [00:34<08:15,  3.79it/s][A2024-10-28 21:18:59,483 | ERROR | Error in batch 95: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   5%|▍         | 96/1975 [00:34<08:33,  3.66it/s][A2024-10-28 21:18:59,756 | ERROR | Error in batch 96: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   5%|▍         | 97/1975 [00:34<08:33,  3.66it/s][A2024-10-28 21:18:59,946 | ERROR | Error in batch 97: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   5%|▍         | 98/1975 [00:34<07:45,  4.03it/s][A2024-10-28 21:19:00,178 | ERROR | Error in batch 98: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   5%|▌         | 99/1975 [00:35<07:36,  4.11it/s][A2024-10-28 21:19:00,444 | ERROR | Error in batch 99: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   5%|▌         | 100/1975 [00:35<07:49,  4.00it/s][A2024-10-28 21:19:00,928 | ERROR | Error in batch 100: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   5%|▌         | 101/1975 [00:35<10:00,  3.12it/s][A2024-10-28 21:19:01,219 | ERROR | Error in batch 101: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   5%|▌         | 102/1975 [00:36<09:43,  3.21it/s][A2024-10-28 21:19:01,375 | ERROR | Error in batch 102: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   5%|▌         | 103/1975 [00:36<08:15,  3.78it/s][A2024-10-28 21:19:01,587 | ERROR | Error in batch 103: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   5%|▌         | 104/1975 [00:36<07:46,  4.01it/s][A2024-10-28 21:19:02,378 | ERROR | Error in batch 104: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   5%|▌         | 105/1975 [00:37<12:49,  2.43it/s][A2024-10-28 21:19:02,599 | ERROR | Error in batch 105: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   5%|▌         | 106/1975 [00:37<11:02,  2.82it/s][A2024-10-28 21:19:02,858 | ERROR | Error in batch 106: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   5%|▌         | 107/1975 [00:37<10:08,  3.07it/s][A2024-10-28 21:19:03,103 | ERROR | Error in batch 107: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   5%|▌         | 108/1975 [00:38<09:23,  3.32it/s][A2024-10-28 21:19:03,572 | ERROR | Error in batch 108: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   6%|▌         | 109/1975 [00:38<10:56,  2.84it/s][A2024-10-28 21:19:03,788 | ERROR | Error in batch 109: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   6%|▌         | 110/1975 [00:38<09:39,  3.22it/s][A2024-10-28 21:19:04,019 | ERROR | Error in batch 110: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   6%|▌         | 111/1975 [00:39<08:55,  3.48it/s][A2024-10-28 21:19:04,223 | ERROR | Error in batch 111: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   6%|▌         | 112/1975 [00:39<08:08,  3.82it/s][A2024-10-28 21:19:04,905 | ERROR | Error in batch 112: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   6%|▌         | 113/1975 [00:39<12:03,  2.57it/s][A2024-10-28 21:19:05,121 | ERROR | Error in batch 113: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   6%|▌         | 114/1975 [00:40<10:26,  2.97it/s][A2024-10-28 21:19:05,400 | ERROR | Error in batch 114: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   6%|▌         | 115/1975 [00:40<09:53,  3.13it/s][A2024-10-28 21:19:05,656 | ERROR | Error in batch 115: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   6%|▌         | 116/1975 [00:40<09:18,  3.33it/s][A2024-10-28 21:19:05,772 | ERROR | Error in batch 116: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   6%|▌         | 117/1975 [00:40<07:34,  4.08it/s][A2024-10-28 21:19:06,035 | ERROR | Error in batch 117: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   6%|▌         | 118/1975 [00:41<07:44,  3.99it/s][A2024-10-28 21:19:06,313 | ERROR | Error in batch 118: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   6%|▌         | 119/1975 [00:41<08:00,  3.86it/s][A2024-10-28 21:19:06,547 | ERROR | Error in batch 119: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   6%|▌         | 120/1975 [00:41<07:45,  3.98it/s][A2024-10-28 21:19:07,058 | ERROR | Error in batch 120: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   6%|▌         | 121/1975 [00:42<10:10,  3.04it/s][A2024-10-28 21:19:07,266 | ERROR | Error in batch 121: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   6%|▌         | 122/1975 [00:42<09:02,  3.41it/s][A2024-10-28 21:19:07,472 | ERROR | Error in batch 122: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   6%|▌         | 123/1975 [00:42<08:14,  3.75it/s][A2024-10-28 21:19:07,837 | ERROR | Error in batch 123: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   6%|▋         | 124/1975 [00:42<09:08,  3.38it/s][A2024-10-28 21:19:08,291 | ERROR | Error in batch 124: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   6%|▋         | 125/1975 [00:43<10:35,  2.91it/s][A2024-10-28 21:19:08,628 | ERROR | Error in batch 125: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   6%|▋         | 126/1975 [00:43<10:31,  2.93it/s][A2024-10-28 21:19:08,827 | ERROR | Error in batch 126: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   6%|▋         | 127/1975 [00:43<09:12,  3.35it/s][A2024-10-28 21:19:09,087 | ERROR | Error in batch 127: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   6%|▋         | 128/1975 [00:44<08:50,  3.48it/s][A2024-10-28 21:19:09,635 | ERROR | Error in batch 128: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   7%|▋         | 129/1975 [00:44<11:14,  2.74it/s][A2024-10-28 21:19:09,859 | ERROR | Error in batch 129: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   7%|▋         | 130/1975 [00:44<09:56,  3.09it/s][A2024-10-28 21:19:10,038 | ERROR | Error in batch 130: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   7%|▋         | 131/1975 [00:45<08:35,  3.57it/s][A2024-10-28 21:19:10,250 | ERROR | Error in batch 131: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   7%|▋         | 132/1975 [00:45<07:58,  3.85it/s][A2024-10-28 21:19:10,635 | ERROR | Error in batch 132: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   7%|▋         | 133/1975 [00:45<09:07,  3.37it/s][A2024-10-28 21:19:10,876 | ERROR | Error in batch 133: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   7%|▋         | 134/1975 [00:45<08:35,  3.57it/s][A2024-10-28 21:19:11,234 | ERROR | Error in batch 134: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   7%|▋         | 135/1975 [00:46<09:18,  3.30it/s][A2024-10-28 21:19:11,644 | ERROR | Error in batch 135: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   7%|▋         | 136/1975 [00:46<10:16,  2.98it/s][A2024-10-28 21:19:12,259 | ERROR | Error in batch 136: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   7%|▋         | 137/1975 [00:47<12:50,  2.38it/s][A2024-10-28 21:19:12,447 | ERROR | Error in batch 137: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   7%|▋         | 138/1975 [00:47<10:43,  2.86it/s][A2024-10-28 21:19:12,683 | ERROR | Error in batch 138: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   7%|▋         | 139/1975 [00:47<09:39,  3.17it/s][A2024-10-28 21:19:12,884 | ERROR | Error in batch 139: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   7%|▋         | 140/1975 [00:47<08:36,  3.56it/s][A2024-10-28 21:19:13,383 | ERROR | Error in batch 140: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   7%|▋         | 141/1975 [00:48<10:35,  2.89it/s][A2024-10-28 21:19:13,579 | ERROR | Error in batch 141: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   7%|▋         | 142/1975 [00:48<09:12,  3.32it/s][A2024-10-28 21:19:13,753 | ERROR | Error in batch 142: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   7%|▋         | 143/1975 [00:48<08:02,  3.80it/s][A2024-10-28 21:19:14,048 | ERROR | Error in batch 143: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   7%|▋         | 144/1975 [00:49<08:19,  3.66it/s][A2024-10-28 21:19:14,629 | ERROR | Error in batch 144: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   7%|▋         | 145/1975 [00:49<11:08,  2.74it/s][A2024-10-28 21:19:14,831 | ERROR | Error in batch 145: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'
Traceback (most recent call last):
  File "/iitjhome/m23csa016/meesho_code/clipvit_uf_hyper_tune_val.py", line 473, in train_model_with_validation
    for param, grad in zip(model.parameters(), model.gradients):
  File "/iitjhome/m23csa016/.conda/envs/meesho/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CategoryAwareAttributePredictor' object has no attribute 'gradients'

Epoch 1/40 [Train]:   7%|▋         | 146/1975 [00:49<09:38,  3.16it/s][A